project_name: traefik-certs-dumper

builds:
  - binary: traefik-certs-dumper
    ldflags:
      - -s -w -X github.com/ldez/traefik-certs-dumper/cmd.version={{.Version}} -X github.com/ldez/traefik-certs-dumper/cmd.commit={{.ShortCommit}} -X github.com/ldez/traefik-certs-dumper/cmd.date={{.Date}}
    env:
      - GO111MODULE=on
    goos:
      - linux
      - darwin
      - windows
      - freebsd
      - openbsd
    goarch:
      - amd64
      - 386
      - arm
      - arm64
    goarm:
      - 7
      - 6
      - 5

    ignore:
      - goos: darwin
        goarch: 386

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^doc:'
      - '^chore:'
      - '^test:'
      - '^tests:'

archive:
  name_template: '{{ .ProjectName }}_v{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
  format: tar.gz
  format_overrides:
    - goos: windows
      format: zip
  files:
    - LICENSE

#release:
#  disable: true